### ISSUE TITLE
大佬，请问要怎么更改用户信息，比如新增或者删除某些字段了？

### ISSUE THREAD

**Issue by varkai** [known/Known#1]
RT

**Comment by known** [comment]
想要自定义用户管理模块的字段栏位吗？

**Comment by varkai** [comment]
是的

**Comment by known** [comment]
有两种方式：
1. 往框架注入自定义内容，这个后续版本可考虑支持
2. 重新写一个页面，用户管理菜单是在模块管理中配置的可以更改，保存数据同时往框架用户表同步一份数据

**Comment by varkai** [comment]
> 

好的，谢谢大佬的解答。
另外可以可以直接在Known框架代码的基础上开发了，这样就可以直接修改了
